### PR TITLE
Use explicit pathType values for Ingress

### PR DESCRIPTION
**Pull request by jimmykarily**
to avoid unexpected implementations. Also move the "catch all" rule at
the end because in some cases it seems to matter (See:
https://github.com/epinio/epinio/issues/1663#issuecomment-1206834066)

Sibling PR: https://github.com/epinio/epinio/pull/1685

### CODE REVIEW

**Comment by andreas-kupries** [comment]
@jimmykarily Should we rebase and update the `standard-stateful` chart also ? Or do that separately ?

**Comment by andreas-kupries** [comment]
Ignore that comment please. I seem to have confused the system ingress changed here with the app ingresses from the app chart.

**Comment by jimmykarily** [comment]
> Ignore that comment please. I seem to have confused the system ingress changed here with the app ingresses from the app chart.

either this, or I had actually changed the application chart too and later reverted, I don't remember. All good.

**Review by andreas-kupries — APPROVED** [review]
looks ok

**Pull request merged**
