### PR TITLE
fix: updated kubed default values

### LINKED ISSUE #533: Bundled `kubed` doesn't install properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

_No response_

### Logs

_No response_

### Anything else?

Please see epinio/epinio/issues/2753 for details

### PR DESCRIPTION
**Pull request by scuba10steve**
fix #533 

Please let me know if there are any additional changes necessary, I do believe this will alleviate the issue.

### CODE REVIEW

**Comment by krumware** [comment]
It might be a good idea to go ahead and add the tag as well, but this looks good from my end after having the same issue.

**Comment by krumware** [comment]
I used the following with success:

```yaml
kubed:
  enableAnalytics: false
  enabled: true
  fullnameOverride: kubed
  operator:
    registry: rancher
    repository: mirrored-appscode-kubed
    tag: v0.13.2
```

**Comment by scuba10steve** [comment]
> It might be a good idea to go ahead and add the tag as well, but this looks good from my end after having the same issue.

Only reason I left the version out was so it could be specified elsewhere like it is today, but I have no problem putting it in.

**Review by olblak — APPROVED** [review]

**Comment by enrichman** [comment]
Thanks @scuba10steve @krumware 

I was not able to update this PR/branch, so I opened a new one: https://github.com/epinio/helm-charts/pull/536

Closing this one.

**Comment by scuba10steve** [comment]
> Thanks @scuba10steve @krumware
> 
> I was not able to update this PR/branch, so I opened a new one: #536
> 
> Closing this one.

Ah I didn't see this until today,  I appreciate the heads up!

**Pull request closed without merging**
