### PR TITLE
Fix non use of `server.ingressClassName` by templates

### PR DESCRIPTION
**Pull request by andreas-kupries**
ref: https://github.com/epinio/epinio/issues/1954
epinio import via https://github.com/epinio/epinio/pull/1963

:notes:  this is the ingress class to pass to applications
:memo:  spacing in values.yaml, to enhance readability (separate sections by empty lines)
:hammer: :bug:  typo in same

### CODE REVIEW

**Comment by enrichman** [comment]
I'm not a big fan of the mixed uppercase titles, i.e. `Start With An Issue` vs `Start with an issue`. Also in the other pages we have the old format I think. @nunix do we have a general guideline here?

**Comment by enrichman** [comment]
LGTM, I was just wondering if a `server.appIngressClassName` would be more explicit than the `server.ingressClassName`.

**Comment by andreas-kupries** [comment]
Most likely yes. I certainly was confused when I saw this.

**Comment by andreas-kupries** [comment]
It would also be an API change (for operators/installers)

**Comment by enrichman** [comment]
Ah sorry, I thought that it was a new value. I was confused by the Github's diff.

Also if it was not used I would probably try to avoid API changes so.. yep, let's keep it like this. The comment is explaining it, and the `ingressClassName` seems to be pretty standard as a key.

**Review by enrichman — APPROVED** [review]

**Pull request merged**
